jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use the Node.js version your project requires (e.g., 18, 20)

      - name: Install dependencies
        run: npm ci # Use 'npm ci' for a clean install, or 'npm install' if preferred

      - name: Build
        run: npm run build # Replace with your build command (e.g., 'npm run build' for React)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/ # Path to the built files (adjust if your build output is in a different folder)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
